---
openapi: 3.0.0
info:
  title: API for getting blocks
  description: API for booking spare fridge blocks and calculation price
  contact:
    name: Dmitry
    email: d28052003@gmail.com
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/d28052003/FridgeMaster/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /login:
    post:
      description: Login user as customer for getting access to account
      parameters:
      - name: login
        in: query
        description: Login from customer
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: mr-vito-scalette
      - name: password
        in: query
        description: Password from customer
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: klfsjflshdfk908098
      responses:
        "200":
          description: Customer was successfully logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "401":
          description: Customer entered wrong password or login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401'
  /register:
    post:
      description: SignUp user as customer for getting access to account
      parameters:
      - name: login
        in: query
        description: Unique Login for creating new account
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: mr-vito-scalette
      - name: password
        in: query
        description: Password from customer
        required: true
        style: form
        explode: true
        schema:
          minLength: 8
          type: string
          example: klfsjflshdfk908098
      responses:
        "200":
          description: Customer's account was successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
  /logout:
    get:
      description: Logout from current customer account
      responses:
        "200":
          description: User was successfully logged out
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
  /locations:
    get:
      description: Get all spare blocks and information about locations
      responses:
        "200":
          description: Successfully get all information about locations and spare blocks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
  /calculation:
    post:
      description: Calculate price and amount of blocks
      parameters:
      - name: location_slug
        in: query
        description: Slug of location with blocks
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: valencia
      - name: temperature
        in: query
        description: Temperature in blocks (will be offered blocks with +-2 deg)
        required: true
        style: form
        explode: true
        schema:
          maximum: 0
          exclusiveMaximum: true
          type: number
          example: -10.9
      - name: volume
        in: query
        description: Volume for placing into blocks (in cubic meters)
        required: true
        style: form
        explode: true
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: number
          example: 40.202
      - name: start_rent
        in: query
        description: Date of starting booking period
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: date
          example: 2022-06-10
      - name: end_rent
        in: query
        description: Date of ending booking period
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: date
          example: 2022-06-25
      responses:
        "200":
          description: Successfully calculated imaginary booking
          content:
            aplication/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
        "403":
          description: Don't have enough blocks or user's data isn't acceptable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_403'
  /customers/orders:
    get:
      description: Get all orders of customer from orders database
      responses:
        "200":
          description: Successful pull of current customer orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_5'
        "401":
          description: Customer isn't authentificated
      security:
      - cookieAuth: []
    post:
      description: Make new order in defined location from list
      parameters:
      - name: location_slug
        in: query
        description: Slug of location with blocks
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: valencia
      - name: temperature
        in: query
        description: Temperature in blocks (will be offered blocks with +-2 deg)
        required: true
        style: form
        explode: true
        schema:
          maximum: 0
          exclusiveMaximum: true
          type: number
          example: -10.9
      - name: volume
        in: query
        description: Volume for placing into blocks (in cubic meters)
        required: true
        style: form
        explode: true
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: number
          example: 40.202
      - name: start_rent
        in: query
        description: Date of starting booking period
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: date
          example: 2022-06-10
      - name: end_rent
        in: query
        description: Date of ending booking period
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: date
          example: 2022-06-25
      responses:
        "200":
          description: Successful booking spare blocks for needed volume
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_6'
        "401":
          description: Customer isn't authentificated
      security:
      - cookieAuth: []
  /customers/orders/{id}:
    get:
      description: Get customer's order by its ID
      parameters:
      - name: id
        in: path
        description: ID of order which is need to update
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 2
      responses:
        "200":
          description: Successful getting information about order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_7'
        "401":
          description: Customer does't have acces to this order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401_1'
      security:
      - cookieAuth: []
    put:
      description: Change old order (booking) identified by ID
      parameters:
      - name: id
        in: path
        description: ID of order which is need to update
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 2
      - name: temperature
        in: query
        description: Temperature in blocks (will be offered blocks with +-2 deg)
        required: true
        style: form
        explode: true
        schema:
          maximum: 0
          exclusiveMaximum: true
          type: number
          example: -10.9
      - name: volume
        in: query
        description: Volume for placing into blocks (in cubic meters)
        required: true
        style: form
        explode: true
        schema:
          minimum: 0
          exclusiveMinimum: true
          type: number
          example: 40.202
      - name: start_rent
        in: query
        description: Date of starting booking period
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: date
          example: 2022-06-10
      - name: end_rent
        in: query
        description: Date of ending booking period
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: date
          example: 2022-06-25
      responses:
        "200":
          description: Successful booking spare blocks for needed volume
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_7'
        "401":
          description: Customer does't have acces to this order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401_1'
      security:
      - cookieAuth: []
    delete:
      description: Disable customer's order or terminating booking by changing status parameter
      parameters:
      - name: id
        in: path
        description: ID of order which is need to update
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          example: 2
      - name: temperature
        in: query
        description: Temperature in blocks (will be offered blocks with +-2 deg)
        required: true
        style: form
        explode: true
        schema:
          type: number
          example: -10.9
      - name: volume
        in: query
        description: Volume for placing into blocks (in cubic meters)
        required: true
        style: form
        explode: true
        schema:
          type: number
          example: 40.202
      - name: start_rent
        in: query
        description: Date of starting book period
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: date
          example: 2022-06-10
      - name: end_rent
        in: query
        description: Date of ending book period
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: date
          example: 2022-06-25
      responses:
        "200":
          description: Successful booking spare blocks for needed volume
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
        "401":
          description: Customer does't have acces to this order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401_1'
      security:
      - cookieAuth: []
components:
  schemas:
    order:
      type: object
      properties:
        id:
          type: integer
          example: 2
        location:
          $ref: '#/components/schemas/order_location'
        status:
          type: boolean
          example: true
        start_rent:
          type: string
          example: 2022-06-10
        end_rent:
          type: string
          example: 2022-06-25
        left_days:
          type: integer
          example: 10
        bill:
          type: number
          example: 4000
        access_token:
          type: string
          example: VFnjb9QWqbi5
        need_to_take:
          type: boolean
          example: false
        blocks:
          type: array
          items:
            $ref: '#/components/schemas/order_blocks'
    inline_response_200:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: You are logged in!
    inline_response_401:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: Password or login is wrong!
    inline_response_200_1:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: You were successfully signed up!
    inline_response_200_2:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: You are logged out!
    inline_response_200_3:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_3_data'
    inline_response_200_4:
      type: object
      properties:
        calculation:
          $ref: '#/components/schemas/inline_response_200_4_calculation'
    inline_response_403:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: ""
    inline_response_200_5:
      type: object
      properties:
        customer:
          $ref: '#/components/schemas/inline_response_200_5_customer'
    inline_response_200_6:
      type: object
      properties:
        order:
          $ref: '#/components/schemas/inline_response_200_6_order'
    inline_response_200_7:
      type: object
      properties:
        order:
          $ref: '#/components/schemas/order'
    inline_response_401_1:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: boolean
          example: false
    order_location:
      type: object
      properties:
        location_name:
          type: string
          example: Valencia
        location_slug:
          type: string
          example: valencia
        spare_blocks_count:
          type: integer
          example: 10
        spare_volume:
          type: integer
          example: 20
      example: null
    order_blocks:
      type: object
      properties:
        temperature:
          type: number
          example: -10.9
        id:
          type: integer
          example: 29
      example: null
    inline_response_200_3_data:
      type: object
      properties:
        location_name:
          type: string
          example: Toronto
        location_slug:
          type: string
          example: toronto
        count_blocks:
          type: integer
          example: 170
        spare_volume:
          type: number
          example: 340
      example: null
    inline_response_200_4_calculation_blocks:
      type: object
      properties:
        id:
          type: integer
          example: 10
        tempeature:
          type: number
          example: -11.2
      example: null
    inline_response_200_4_calculation:
      type: object
      properties:
        enough_block:
          type: boolean
          example: true
        total_price:
          type: number
          example: 4000
        term:
          type: integer
          example: 15
        locaion:
          type: string
          example: Valencia
        needed_block:
          type: integer
          example: 21
        blocks:
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_4_calculation_blocks'
      example: null
    inline_response_200_5_customer:
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: '#/components/schemas/order'
      example: null
    inline_response_200_6_order:
      type: object
      properties:
        id:
          type: integer
          example: 2
        location:
          $ref: '#/components/schemas/order_location'
        status:
          type: boolean
          example: true
        start_rent:
          type: string
          example: 2022-06-10
        end_rent:
          type: string
          example: 2022-06-25
        left_days:
          type: integer
          example: 10
        bill:
          type: number
          example: 4000
        access_token:
          type: string
          example: VFnjb9QWqbi5
        need_to_take:
          type: boolean
          example: false
        blocks:
          type: array
          items:
            $ref: '#/components/schemas/order_blocks'
      example: null
  securitySchemes:
    cookieAuth:
      type: apiKey
      name: fridgemaster_session
      in: cookie
